version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/ceri-m1-technique-de-test
    steps:
      - checkout
      - run: mvn test
    branches:
      only:
        - master
