version: 2.1

orbs:
  codecov: codecov/codecov@3.2.4

jobs:
  build_and_test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
      - codecov/upload
  docs:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run:
          name: Adding OpenJDK-PPA
          command: sudo add-apt-repository ppa:openjdk-r/ppa
      - run:
          name: Update apt
          command: sudo apt-get update
      - run:
          name: Installation of OpenJDK
          command: sudo apt-get install openjdk-11-jdk-headless -y
      - run:
          name: Building JavaDocs
          command: javadoc -d docs src/main/java/fr/univavignon/pokedex/api/*
      - persist_to_workspace:
          root: .
          paths: docs
  docs-deploy:
    docker:
      - image: node:20
    steps:
      - checkout
      - attach_workspace:
          at: docs/
      - run:
          name: Install and configure dependencies
          command:  |
            npm install -g --silent gh-pages@3.0.0
            git config --global user.email "aspa.thomas@gmail.com"
            git config --global user.name "aspathomas"
      - add_ssh_keys:
          fingerprints:
            - "11:6b:11:59:ef:94:3b:57:5d:d9:da:06:1e:aa:e7:ef"
      - run:
          name: Deployment of documents in the gh-pages branch
          command: gh-pages --dist docs/

workflows:
  build_and_test:
    jobs:
      - build_and_test:
        filters:
            branches:
              only: master
      - docs
      - docs-deploy:
          requires:
            - docs