version: 2.1

jobs:

  build_and_test:
    docker:
      - image: cimg/openjdk:11.0

    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package

      - run:
          name: Test
          command: mvn test
      - name: Upload coverage reports to Codecov
          uses: codecov/codecov-action@v3
          with:
            token: ${{ secrets.CODECOV_TOKEN }}


workflows:
  build_and_test:
    jobs:
      - build_and_test:
        filters:
          branches:
            only: master