version: 2.1

orbs:
  codecov: codecov/codecov@3.2.4
jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
      - codecov/upload
  docs:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run:
          name: Adding OpenJDK-PPA
          command: sudo add-apt-repository ppa:openjdk-r/ppa
      - run:
          name: Update apt
          command: sudo apt-get update
      - run:
          name: Installation of OpenJDK
          command: sudo apt-get install openjdk-11-jdk-headless -y
      - run:
          name: Build-docs
          command: javadoc src/main/java/fr/univavignon/pokedex/api/* -d docs
      - persist_to_workspace:
          root: .
          paths: docs

  docs-deploy:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: docs/
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "aspa.thomas@gmail.com"
            git config user.name "thomas_aspa"
      - run:
          name: Deploy docs to gh-pages branch
          command: |
            git remote remove origin
            git remote add origin https://aspathomas:${JAVA_DOC_TOKEN}@github.com/aspathomas/ceri-m1-techniques-de-test.git
            gh-pages --dist docs/


workflows:
  build-and-test:
    jobs:
      - build-and-test
      - docs
      - docs-deploy:
          requires:
            - build-and-test
            - docs
          filters:
            branches:
              only: master